# Generated by Django 5.0.4 on 2024-04-04 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_user',
            fields=[
                ('Blog_User_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('Email_ID', models.EmailField(max_length=254)),
                ('contc_no', models.IntegerField(null=True)),
                ('BirthDate', models.DateField(null=True)),
                ('Picture', models.ImageField(upload_to='user_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Blog_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog_user')),
            ],
        ),
    ]
